version: '3.4'

x-environment:
  &shared-envvar
  - POSTGRES_USER: "klubok"
  - POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  - DATABASE_URL: "postgis://klubok:${POSTGRES_PASSWORD}@db:5432/postgres"

services:

  db:
    image: postgis/postgis:15-3.3-alpine
    environment:
      << : *shared-envvar
    # volumes:
    #   - ./misc/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: klubok-backend
    build: .
    environment:
      << : *shared-envvar
      ALLOWED_HOSTS: '["localhost"]'
      CORS_ALLOWED_ORIGINS: '["http://localhost"]'
    ports:
      - "80:80"
    volumes:
      - ./klubok:/code/klubok/
    depends_on:
      - db
