# Generated by Django 2.2.28 on 2022-10-30 14:06
import typing as ty
import uuid

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: ty.List[str] = []

    operations = [
        migrations.CreateModel(
            name="PlacePricerange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PlaceTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1024)),
                ("url_img", models.URLField(max_length=512)),
                (
                    "rating",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "priceranges",
                    models.ManyToManyField(
                        related_name="places", to="geoplaces.PlacePricerange"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="places", to="geoplaces.PlaceTag"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        related_name="places", to="geoplaces.PlaceType"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
