# Generated by Django 2.2.28 on 2022-10-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geoplaces", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="place",
            name="promo_code",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        )
    ]
