# Generated by Django 4.1.3 on 2022-11-03 14:20

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geoplaces", "0004_alter_place_description_alter_place_priceranges_and_more")
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["location"], name="geoplaces_p_locatio_1828d7_gist"
            ),
        )
    ]
